### ISSUE TITLE
EasyCompressor and EasyCaching

### ISSUE THREAD

**Issue by jasenf** [mjebrahimi/EasyCompressor#103]
Is it possible to use EasyCompressor with EasyCaching's in-memory caching?  We have tried and it doesn't seem to be doing any compression.  I have a 2MB HTML file I am trying to compress locally and when I interrogate the in-memory cache, the byte array still seems to be the same size.    If I flip it to use Redis, the cache entry in Redis compresses down to 150k so I think maybe the in-memory providers are ignoring the compression step, even when I request to use JSON.  This is my setup:

```
services.AddGZipCompressor("gzip");
services.AddEasyCaching(option => { 
          option
          .UseInMemory(config =>
                            {
                                config.DBConfig = new InMemoryCachingOptions
                                                  {
                                                      ExpirationScanFrequency = 300,
                                                      SizeLimit = 10000000,
                                                      EnableReadDeepClone = true,
                                                      EnableWriteDeepClone = true
                                                  };
                                config.EnableLogging = configuration["Logging:Cache"]
                                    .ToBoolean();
                                config.LockMs = 5000;
                                config.SleepMs = 300;
                                config.SerializerName = "pagememoryjson";
                            },
                            pageMemoryProvider)
                           .WithJson("pagememoryjson")
                           .WithCompressor("pagememoryjson","gzip");
```

**Comment by mjebrahimi** [comment]
It is not possible to compress with the in-memory provider because the in-memory caching provider does not use a serializer and [stores the object without serializing it](https://github.com/dotnetcore/EasyCaching/blob/159a9306538dcef59a714a8d17465197ba5b4417/src/EasyCaching.InMemory/Internal/InMemoryCaching.cs#L336).
