### ISSUE TITLE
BrotliCompressor for FW 4.8

### ISSUE THREAD

**Issue by LexaGV** [mjebrahimi/EasyCompressor#201]
I work on .NET FW 4.8; I read "EasyCompressor.BrotliNET (deprecated)" - can you explain more descriptively, what it means? It's not developed anymore (code is old) or it's "deprecated" just because somebody in MS decide FW 4.8 is "old"? I see no logical link for "deprecation" word.

In other words: may I expect `EasyCompressor.BrotliNET` code is the same as in main line?

Second problem: `EasyCompressor.BrotliNET` depends from some `Brotli.Core, Version=2.1.1.0` - what and where it is?

**Comment by mjebrahimi** [comment]
Hi @LexaGV,
No, it has nothing to do with .NET 4.8 and Nobody has said that .NET 4.8 is obsolete ;) (even Microsoft itself) 
This package uses [Brotli.NET](https://www.nuget.org/packages/Brotli.NET/) as underlying, and as you can see from its [Github repository](https://github.com/XieJJ99/brotli.net) it's discontinued and it will no longer be developed and maintained. (more than 3 years ago)
So I also decided not to develop and maintain `EasyCompressor.BrotliNET` anymore.

**Comment by mjebrahimi** [comment]
1. Untile now `EasyCompressor.BrotliNET` (v2.0.2) code base is the same as main line.
2. `EasyCompressor.BrotliNET` depends on these two packages:
[Brotli.NET](https://www.nuget.org/packages/Brotli.NET/) (>= 2.1.1) - ([Github](https://github.com/XieJJ99/brotli.net))
[EasyCompressor](https://www.nuget.org/packages/EasyCompressor/) (>= 2.0.2)

**Comment by LexaGV** [comment]
Thanks, Mohammad! Only now got full pic - Brotli.NET is needed (not explained in ReadMe). But after I assembled full app (including _native_ lib `brolib_x64.dll`), I got even worse result:

```
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Argument bytes must be not empty.
Parameter name: bytes
   at EasyCompressor.Guard.ThrowIfNullOrEmpty[T](IEnumerable`1 enumerable, String paramName) in /_/src/EasyCompressor/Utilities/Guard.cs:line 68
   at EasyCompressor.BaseCompressor.Compress(Byte[] bytes) in /_/src/EasyCompressor/Compressors/Base/BaseCompressor.cs:line 72
```

I guess this error happen even before running into Brotli.NET. Can you please look at it? I try to use Brotli compressor (as one of the fastest), but fail so far. :(

My demo code is simple:

```
var compressor = BrotliNETCompressor.Shared;
Parallel.ForEach(... on each file in folder...)
{
    smth = compressor.Compress(data);// data is byte[]
}
```

`BrotliNETCompressor.Shared` declared as thread safe, but... can I **use** one instance for all threads?! (theoretically I should!)

**Comment by mjebrahimi** [comment]
Yes, the `Shared` instance is thread-safe and you can use this among all your threads.
About the error, as it explains your byte array is empty, I guess one of your files is empty. (size of zero bytes)
Please make sure about it and if the error has remained create a **reproducible sample** and send it here.

**Comment by LexaGV** [comment]
Cool, you're right! For me it was also surprise that file is zero. No problem, my fault. :) Thanks for help!
